server:
  port: 8088
  servlet:
    session:
      timeout: 30s
spring:
  application:
    name: spring-security-demo
  datasource:
    url: jdbc:mysql://59.110.19.191:3306/spring-security?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: zhangxp
    password: 7324368Best!@
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:com/zhangxp/spring/security/bankend/resource/mapper/*.xml